services:
  nginx:
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
      - ./data-cache:/data/nginx/cache
    ports:
      - "80:80"
  server:
    build: ./server
    ports:
      - "8080:8080"
    container_name: server_test
